# See this page for descriptions:
# https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md

ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[directive.specify-disable-reason]
[rule.context-keys-type]
[rule.time-naming]
[rule.var-declaration]
[rule.unexported-return]
[rule.errorf]
[rule.blank-imports]
[rule.context-as-argument]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
# [rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.indent-error-flow]
[rule.argument-limit]
  arguments = [5]
[rule.cyclomatic]
  arguments = [10]
[rule.max-public-structs]
  arguments = [4]
[rule.empty-block]
[rule.superfluous-else]
[rule.confusing-naming]
[rule.get-return]
[rule.modifies-parameter]
[rule.confusing-results]
[rule.deep-exit]
[rule.unused-parameter]
[rule.unreachable-code]
# [rule.add-constant]
#   arguments = [{maxLitCount = "10",allowStrs ="\"\"",allowInts="0,1,2,3,4,5,6,7,8,9,16,24,32,40,48,56,64,128,256,0xff",allowFloats="0.0,0.,1.0,1.,2.0,2."}]
[rule.flag-parameter]
[rule.unnecessary-stmt]
[rule.struct-tag]
[rule.modifies-value-receiver]
[rule.constant-logical-expr]
[rule.bool-literal-in-expr]
[rule.redefines-builtin-id]
[rule.function-result-limit]
  arguments = [4]
[rule.imports-blacklist]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.waitgroup-by-value]
[rule.atomic]
[rule.empty-lines]
[rule.line-length-limit]
  arguments = [120]
[rule.call-to-gc]
[rule.duplicated-imports]
[rule.import-shadowing]
[rule.bare-return]
[rule.unused-receiver]
[rule.unhandled-error]
  arguments = ["sb.WriteString"]
  severity = "error"
[rule.cognitive-complexity]
  arguments = [7]
[rule.string-of-int]
