version: "3"

services:
  rideshare-go-ap-south:
    ports:
      - 5000
    hostname: rideshare-go-ap-south
    environment: &env
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
      OTLP_URL: tempo:4318
      OTLP_INSECURE: 1
      DEBUG_LOGGER: 1
      REGION: ap-south
    build:
      context: ../../language-sdk-instrumentation/golang-push/rideshare

  rideshare-go-eu-north:
    ports:
      - 5000
    hostname: rideshare-go-eu-north
    environment:
      <<: *env
      REGION: eu-north
    build:
      context: ../../language-sdk-instrumentation/golang-push/rideshare

  rideshare-java-us-east:
    ports:
      - 5000
    hostname: rideshare-java-us-east
    environment:
      <<: *env
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_SERVICE_NAME: rideshare.java.push.app
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_SAMPLER: always_on
      OTEL_PROPAGATORS: tracecontext
      PYROSCOPE_LABELS: hostname=rideshare-java-us-east
      REGION: us-east
    build:
      context: ../../language-sdk-instrumentation/java/rideshare
      dockerfile: Dockerfile.otel-instrumentation

  rideshare-dotnet-eu-west:
    ports:
      - 5000
    hostname: rideshare-dotnet-eu-west
    environment:
      <<: *env
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_SERVICE_NAME: rideshare.dotnet.push.app
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_SAMPLER: always_on
      OTEL_PROPAGATORS: tracecontext
      OTEL_RESOURCE_ATTRIBUTES: host.name=rideshare-dotnet-eu-west
      PYROSCOPE_LABELS: hostname=rideshare-dotnet-eu-west
      REGION: eu-west
    build:
      context: ../../language-sdk-instrumentation/dotnet/rideshare-otel
      dockerfile: Dockerfile

  rideshare-dotnet-eu-south:
    ports:
      - 5000
    hostname: rideshare-dotnet-eu-south
    environment:
      <<: *env
      PYROSCOPE_LABELS: hostname=rideshare-dotnet-eu-south
      REGION: eu-north
      JAEGER_SERVICE_NAME: rideshare.dotnet.opentracing.push.app
      JAEGER_AGENT_HOST: tempo
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1.0
      JAEGER_REPORTER_LOG_SPANS: true
    build:
      context: ../../language-sdk-instrumentation/dotnet/rideshare-opentracing
      dockerfile: Dockerfile

  load-generator:
    environment: *env
    build:
      context: ../../language-sdk-instrumentation/golang-push/rideshare
      dockerfile: Dockerfile.load-generator
    command:
      - ./loadgen
      - http://rideshare-go-ap-south:5000
      - http://rideshare-go-eu-north:5000
      - http://rideshare-java-us-east:5000
      - http://rideshare-dotnet-eu-west:5000
      - http://rideshare-dotnet-eu-south:5000

  grafana:
    image: grafana/grafana-dev:10.3.0-151740
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=pyroscope-panel
      - GF_FEATURE_TOGGLES_ENABLE=traceToProfiles tracesEmbeddedFlameGraph
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - '3000:3000'

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin

  pyroscope:
    image: grafana/pyroscope:latest
    environment:
      JAEGER_AGENT_HOST: tempo
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    command: [ "-config.file=/etc/pyroscope.yml" ]
    ports:
      - '4040:4040'
    volumes:
      - ./pyroscope/pyroscope.yml:/etc/pyroscope.yml
