x-service: &rideshare-go-template
  ports:
    - 5000
  environment: &env
    PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
    OTLP_URL: tempo:4318
    OTLP_INSECURE: 1
    DEBUG_LOGGER: 1
  build:
    context: ../../language-sdk-instrumentation/golang-push/rideshare

x-environment: &otel
  <<: *env
  OTEL_TRACES_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
  OTEL_METRICS_EXPORTER: none
  OTEL_TRACES_SAMPLER: always_on
  OTEL_PROPAGATORS: tracecontext

services:
  rideshare-go-ap-south:
    <<: *rideshare-go-template
    hostname: rideshare-go-ap-south
    environment:
      REGION: ap-south

  rideshare-go-eu-north:
    <<: *rideshare-go-template
    hostname: rideshare-go-eu-north
    environment:
      REGION: eu-north

  rideshare-java-us-east:
    ports:
      - 5000
    hostname: rideshare-java-us-east
    environment:
      <<: *otel
      OTEL_SERVICE_NAME: rideshare.java.push.app
      PYROSCOPE_LABELS: hostname=rideshare-java-us-east
      REGION: us-east
    build:
      context: ../../language-sdk-instrumentation/java/rideshare
      dockerfile: Dockerfile.otel-instrumentation

  rideshare-dotnet-eu-west:
    ports:
      - 5000
    hostname: rideshare-dotnet-eu-west
    environment:
      <<: *otel
      OTEL_SERVICE_NAME: rideshare.dotnet.push.app
      OTEL_RESOURCE_ATTRIBUTES: host.name=rideshare-dotnet-eu-west
      PYROSCOPE_LABELS: hostname=rideshare-dotnet-eu-west
      REGION: eu-west
    build:
      context: ../../language-sdk-instrumentation/dotnet/rideshare
      dockerfile: Dockerfile

  rideshare-python-eu-east:
    ports:
      - 5000
    hostname: rideshare-python-eu-east
    environment:
      <<: *otel
      OTEL_SERVICE_NAME: rideshare.python.push.app
      PYROSCOPE_LABELS: hostname=rideshare-python-us-east
      REGION: us-east
    build:
      context: ../../language-sdk-instrumentation/python/rideshare/flask
      dockerfile: Dockerfile

  load-generator:
    environment: *env
    build:
      context: ../../language-sdk-instrumentation/golang-push/rideshare
      dockerfile: Dockerfile.load-generator
    command:
      - ./loadgen
      - http://rideshare-go-ap-south:5000
      - http://rideshare-go-eu-north:5000
      - http://rideshare-java-us-east:5000
      - http://rideshare-dotnet-eu-west:5000
      - http://rideshare-python-eu-east:5000

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_FEATURE_TOGGLES_ENABLE=traceToProfiles tracesEmbeddedFlameGraph
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - '3000:3000'

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin

  pyroscope:
    image: grafana/pyroscope:latest
    environment:
      JAEGER_AGENT_HOST: tempo
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    command: [ "-config.file=/etc/pyroscope.yml" ]
    ports:
      - '4040:4040'
    volumes:
      - ./pyroscope/pyroscope.yml:/etc/pyroscope.yml
