apiVersion: v2
name: phlare
description: ðŸ”¥ horizontally-scalable, highly-available, multi-tenant continuous profiling aggregation system
type: application
version: 0.5.2
appVersion: 0.5.1
dependencies:
  - name: minio
    alias: minio
    version: 4.0.12
    repository: https://charts.min.io/
    condition: minio.enabled
