---
log-level: debug
scrape-configs:
  - job-name: consul-services
    enabled-profiles: [cpu, mem, goroutines, mutex, block]
    consul-sd-configs:
      - server: 'consul:8500'
        # Optionally specify the datacenter.
        datacenter: "dc1"
        # You may explicitly list services you want to profile.
        # By default, all discovered services are scraped.
        services:
         - test-service

    relabel-configs:
      # Pyroscope server needs application name (the '__name__' label)
      # to be provided for every profile in order to properly aggregate data.
      - source-labels: [__meta_consul_service]
        action: replace
        target-label: __name__

      # Pyroscope server is not aware of the application language and runtime,
      # if profiling data is pulled from the target. You can optionally specify
      # '__spy_name__' label to indicate it: here we take the value from the
      # 'pyroscope_spy_name' metadata item. By default, Go (gospy) is assumed.
      - source-labels:
          [ __meta_consul_service_metadata_pyroscope_spy_name ]
        action: replace
        target-label: __spy_name__
      - regex: __meta_consul_service_metadata_pyroscope_spy_name
        action: labeldrop

      # Labels that are specific to the consul service discovery (__meta_consul_*)
      # can be used as pyroscope labels.
      - source-labels: [__meta_consul_dc]
        action: replace
        target-label: consul_dc

      # Service metadata can be also mapped to pyroscope labels directly.
      - action: labelmap
        regex: __meta_consul_service_metadata_(.+)
