version: '3.9'
services:
  us-east:
    environment:
      - REGION=us-east
    build:
      context: .

  eu-north:
    environment:
      - REGION=eu-north
    build:
      context: .

  ap-south:
    environment:
      - REGION=ap-south
    build:
      context: .

  pyroscope:
    image: grafana/pyroscope
    environment:
      - PYROSCOPE_LOG_LEVEL=debug
    ports:
      - '4040:4040'
    command:
      - 'server'

  load-generator:
    build:
      context: .
      dockerfile: Dockerfile.load-generator
