services:
  us-east:
    container_name: us-east
    ports:
    - 5000
    environment:
    - REGION=us-east
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - PARAMETERS_POOL_SIZE=1000
    - PARAMETERS_POOL_BUFFER_SIZE_KB=1000
    - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://prometheus:9090/api/v1/otlp/v1/metrics
    build:
      context: .
  eu-north:
    container_name: eu-north
    ports:
    - 5000
    environment:
    - REGION=eu-north
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://prometheus:9090/api/v1/otlp/v1/metrics
    build:
      context: .
  ap-south:
    container_name: ap-south
    ports:
    - 5000
    environment:
    - REGION=ap-south
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://prometheus:9090/api/v1/otlp/v1/metrics
    build:
      context: .
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
    - 4040:4040
  load-generator:
    build:
      context: .
      dockerfile: Dockerfile.load-generator
    environment:
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://prometheus:9090/api/v1/otlp/v1/metrics
  grafana:
    image: grafana/grafana:latest
    environment:
    - GF_PLUGINS_PREINSTALL_SYNC=grafana-pyroscope-app
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
    - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
    - 3000:3000
  prometheus:
    image: prom/prometheus:v3.1.0
    ports:
      - '9099:9090'
    command: >
      --enable-feature=remote-write-receiver
      --enable-feature=exemplar-storage
      --enable-feature=native-histograms
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.enable-otlp-receiver
    volumes:
      - ./prometheus-provisioning/prometheus.yaml:/etc/prometheus/prometheus.yml
