version: '3.9'

services:
  jaeger:
    image: 'jaegertracing/all-in-one:1.31'
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  pyroscope:
    image: 'pyroscope/pyroscope:latest'
    environment:
      - PYROSCOPE_CONFIG=/pyroscope.yaml
      - PYROSCOPE_LOG_LEVEL=debug
    ports:
      - '4040:4040'
    volumes:
      - ./pyroscope.yaml:/pyroscope.yaml
    command:
      - 'server'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  grafana:
    image: pyroscope/grafana:dev
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - 'GF_INSTALL_PLUGINS=pyroscope-panel'
    ports:
      - '3000:3000'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  us-east:
    env_file:
      - config.env
    environment:
      - REGION=us-east
    build:
      context: 'go/rideshare'
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  eu-north:
    env_file:
      - config.env
    environment:
      - REGION=eu-north
    build:
      context: 'go/rideshare'
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  ap-south:
    env_file:
      - config.env
    environment:
      - REGION=ap-south
    build:
      context: 'go/rideshare'
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  us-east-java:
    env_file:
      - config.env
    environment:
      - REGION=us-east
    build:
      context: 'java/rideshare'
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  eu-north-java:
    env_file:
      - config.env
    environment:
      - REGION=eu-north
    build:
      context: 'java/rideshare'
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  ap-south-java:
    env_file:
      - config.env
    environment:
      - REGION=ap-south
    build:
      context: 'java/rideshare'
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  eu-north-java-instrumentation:
    env_file:
      - config.env
    environment:
      - REGION=eu-north
    build:
      context: 'java-instrumentation/rideshare'
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  eu-north-ruby:
    env_file:
      - config.env
    environment:
      - REGION=eu-north
      - SERVER_HOST=eu-north-ruby
    build:
      context: 'ruby/rideshare'
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  load-generator:
    env_file:
      - config.env
    build:
      context: 'go/rideshare'
      dockerfile: Dockerfile.loadgen
    depends_on:
      - ap-south
      - eu-north
      - us-east
      - ap-south-java
      - eu-north-java
      - us-east-java
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  jaeger-ui:
    build:
      context: ''
      dockerfile: jaeger-ui/Dockerfile
    ports:
      - '4000:3000'

  loki:
    image: 'grafana/loki:2.5.0'
    ports:
      - '3100:3100'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'
