version: '3.9'

services:
  jaeger:
    image: 'jaegertracing/all-in-one:1.31'
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '14268:14268'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  pyroscope:
    image: '${PYROSCOPE_IMAGE:-pyroscope/pyroscope-dev:main}'
    environment:
      - PYROSCOPE_CONFIG=/pyroscope.yaml
      - PYROSCOPE_LOG_LEVEL=debug
    ports:
      - '4040:4040'
    volumes:
      - ./pyroscope.yaml:/pyroscope.yaml
    command:
      - 'server'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  grafana:
    image: pyroscope/grafana:dev
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - 'GF_INSTALL_PLUGINS=pyroscope-datasource,pyroscope-panel'
    ports:
      - '3000:3000'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  us-east-1:
    env_file:
      - config.env
    environment:
      - REGION=us-east-1
    build:
      context: ''
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  us-west-1:
    env_file:
      - config.env
    environment:
      - REGION=us-west-1
    build:
      context: ''
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  eu-west-1:
    env_file:
      - config.env
    environment:
      - REGION=eu-west-1
    build:
      context: ''
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  load-generator:
    env_file:
      - config.env
    build:
      context: ''
      dockerfile: Dockerfile.loadgen
    depends_on:
      - eu-west-1
      - us-west-1
      - us-east-1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  jaeger-ui:
    build:
      context: ''
      dockerfile: jaeger-ui/Dockerfile
    ports:
      - '4000:3000'

  loki:
    image: 'grafana/loki:2.5.0'
    ports:
      - '3100:3100'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'
