networks:
  phlare:


services:
  phlare:
    image: grafana/phlare:latest
    ports:
      - "4100:4100"
    command: -config.file=/etc/phlare/config.yaml
    volumes:
      - ./phlare.yaml:/etc/phlare/config.yaml
      - ./data:/data
    networks:
      - phlare

  grafana:
    image: aocenas/grafana:profiling-ds
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - phlare

# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
