{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pyroscope.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- range $.Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - backend:
          service:
            {{- if gt (len $.Values.pyroscope.components) 1}}
            name: {{ include "pyroscope.fullname" $ }}-query-frontend
            {{- else }}
            name: {{ include "pyroscope.fullname" $ }}
            {{- end }}
            port:
              number: {{ $.Values.pyroscope.service.port }}
        path: /
        pathType: Prefix
      - backend:
          service:
            {{- if gt (len $.Values.pyroscope.components) 1}}
            name: {{ include "pyroscope.fullname" $ }}-query-frontend
            {{- else }}
            name: {{ include "pyroscope.fullname" $ }}
            {{- end }}
            port:
              number: {{ $.Values.pyroscope.service.port }}
        path: /querier.v1.QuerierService/
        pathType: ImplementationSpecific
      - backend:
          service:
            {{- if gt (len $.Values.pyroscope.components) 1}}
            name: {{ include "pyroscope.fullname" $ }}-query-frontend
            {{- else }}
            name: {{ include "pyroscope.fullname" $ }}
            {{- end }}
            port:
              number: {{ $.Values.pyroscope.service.port }}
        path: /render
        pathType: Prefix
      - backend:
          service:
            {{- if gt (len $.Values.pyroscope.components) 1}}
            name: {{ include "pyroscope.fullname" $ }}-query-frontend
            {{- else }}
            name: {{ include "pyroscope.fullname" $ }}
            {{- end }}
            port:
              number: {{ $.Values.pyroscope.service.port }}
        path: /render-diff
        pathType: Prefix
      - backend:
          service:
            {{- if gt (len $.Values.pyroscope.components) 1}}
            name: {{ include "pyroscope.fullname" $ }}-distributor
            {{- else }}
            name: {{ include "pyroscope.fullname" $ }}
            {{- end }}
            port:
              number: {{ $.Values.pyroscope.service.port }}
        path: /push.v1.PusherService/
        pathType: ImplementationSpecific
      - backend:
          service:
            {{- if gt (len $.Values.pyroscope.components) 1}}
            name: {{ include "pyroscope.fullname" $ }}-distributor
            {{- else }}
            name: {{ include "pyroscope.fullname" $ }}
            {{- end }}
            port:
              number: {{ $.Values.pyroscope.service.port }}
        path: /ingest
        pathType: Prefix
  {{- end }}
{{- end }}
