{{- if .Values.rustfs.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pyroscope.fullname" . }}-rustfs-create-bucket
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: mb
        image: minio/mc:RELEASE.2025-08-13T08-35-41Z
        command:
        - /bin/bash
        - -c
        - |
          set -euo pipefail
          mc alias set s3 ${S3_ENDPOINT} ${S3_ACCESS_KEY} ${S3_SECRET_KEY}
          mc mb s3/${BUCKET_NAME} --ignore-existing
          echo "Bucket ${BUCKET_NAME} is ready"
        env:
        - name: S3_ENDPOINT
          value: "http://{{ include "pyroscope.fullname" . }}-rustfs-svc:9000"
        - name: S3_ACCESS_KEY
          value: {{ .Values.rustfs.secret.rustfs.access_key | quote }}
        - name: S3_SECRET_KEY
          value: {{ .Values.rustfs.secret.rustfs.secret_key | quote }}
        - name: BUCKET_NAME
          value: "pyroscope-data"
      restartPolicy: Never
  backoffLimit: 32
{{- end }}
