---
apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    uid: jaeger
    url: http://jaeger:16686

  - name: Pyroscope
    type: pyroscope-datasource
    access: proxy
    orgId: 1
    uid: pyroscope
    jsonData:
      path: http://pyroscope:4040

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: 'traceID'
          matcherRegex: "trace_id=(\\w+)"
          url: '$${__value.raw}'
          datasourceUid: jaeger
        - name: 'goProfileExemplar'
          matcherRegex: "go_span_id=(\\w+)"
          url: 'ride-sharing-app.cpu{profile_id="$${__value.raw}"}'
          datasourceUid: pyroscope
        - name: 'javaProfileExemplar'
          matcherRegex: "java_span_id=(\\w+)"
          url: 'ride-sharing-app-java.itimer{profile_id="$${__value.raw}"}'
          datasourceUid: pyroscope
