services:
  us-east:
    ports:
    - 5000
    environment:
    - REGION=us-east
    - PYROSCOPE_SERVER_ADDRESS=http://alloy:9999
    - PARAMETERS_POOL_SIZE=1000
    - PARAMETERS_POOL_BUFFER_SIZE_KB=1000
    build:
      context: .
  eu-north:
    ports:
    - 5000
    environment:
    - REGION=eu-north
    - PYROSCOPE_SERVER_ADDRESS=http://alloy:9999
    build:
      context: .
  ap-south:
    ports:
    - 5000
    environment:
    - REGION=ap-south
    - PYROSCOPE_SERVER_ADDRESS=http://alloy:9999
    build:
      context: .

  alloy:
    image: grafana/alloy:v1.7.1
    command:
      - run
      - /etc/alloy/config.alloy
      - --stability.level=public-preview
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "9999:9999"
      - "12345:12345"

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
    - 4040:4040

  load-generator:
    build:
      context: .
      dockerfile: Dockerfile.load-generator
    environment:
    - PYROSCOPE_SERVER_ADDRESS=http://alloy:9999

  grafana:
    image: grafana/grafana:latest
    environment:
    - GF_PLUGINS_PREINSTALL_SYNC=grafana-pyroscope-app
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
    - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
    - 3000:3000
