storage:
  path: test_storage

sources: 10000
period: 1h
apps:
  test-app.cpu:
    spyName: gospy
    sampleRate: 100
    aggregationType: sum
    units: samples
    trees: 3
    treeConfig:
      maxSymLen: 10
      maxDepth: 30
      width: 5
    tags:
      - name: env
        cardinality: 3
        minLen: 4
        maxLen: 4
      - name: region
        cardinality: 5
        minLen: 4
        maxLen: 7
      - name: version
        cardinality: 4
        minLen: 5
        maxLen: 5
      - name: project
        cardinality: 150
        minLen: 4
        maxLen: 12
      - name: instance
        cardinality: 10000
        minLen: 16
        maxLen: 16
