name: Cloud Compatibility Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cloud_compability_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cloud-compatibility-check
        run: .github/cloud-compatibility-check.rb
        env:
          GITHUB_TOKEN: ${{ secrets.CLOUD_COMPAT_CHECK_GITHUB_TOKEN }}
          GITHUB_SHA: '${{ github.sha }}'
