name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    env:
      ENABLED_SPIES: none
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Cache go mod directories
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
      - run: yarn install
      - run: make -j e2e-build
      - name: store build
        id: store-build
        uses: actions/cache@v3
        with:
          path: bin/pyroscope
          key: ${{ runner.os }}-pyroscope
      - uses: actions/cache@v3
        with:
          path: bin/pyroscope
          key: ${{ runner.os }}-pyroscope
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: http://localhost:4040
          start: make server
          config-file: cypress/cypress.json
        env:
          # keep the server quiet
          PYROSCOPE_LOG_LEVEL: error
          ENABLED_SPIES: none

  cypress-tests-auth:
    runs-on: ubuntu-latest
    env:
      ENABLED_SPIES: none
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Cache go mod directories
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
      - run: yarn install
      - run: make -j e2e-build
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: http://localhost:4040
          start: |
            node ./scripts/oauth-mock/oauth-mock.js
            make server SERVERPARAMS=--config=scripts/oauth-mock/pyroscope-config.yml
          config-file: cypress/integration/auth/cypress.json
        env:
          # keep the server quiet
          PYROSCOPE_LOG_LEVEL: error
          ENABLED_SPIES: none

  cypress-tests-base-url:
    runs-on: ubuntu-latest
    env:
      ENABLED_SPIES: none
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Cache go mod directories
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
      - run: yarn install
      - run: make -j e2e-build
      - name: run nginx with /pyroscope
        run: docker-compose -f cypress/base-url/base-url-docker-compose.yml up -d
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: http://localhost:8080/pyroscope
          start: make server
          config-file: cypress/base-url/cypress.json
        env:
          # keep the server quiet
          PYROSCOPE_BASE_URL: 'http://localhost:8080/pyroscope'
          PYROSCOPE_LOG_LEVEL: error
