name: helm-release

on:
  push:
    branches:
      - main
      - "release-[0-9]+.[0-9]+"

jobs:
  call-update-helm-repo-pyroscope:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@5d1c59cf8ed277f232fd9df56c6b62dd5fca087a
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    with:
      charts_dir: operations/pyroscope/helm/
      cr_configfile: operations/pyroscope/helm/cr.yaml
      ct_configfile: operations/pyroscope/helm/ct.yaml
    secrets:
      vault_repo_secret_name: grafana-pyroscope-releases
  call-update-helm-repo-pyroscope-monitoring:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@5d1c59cf8ed277f232fd9df56c6b62dd5fca087a
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    with:
      charts_dir: operations/pyroscope/helm/
      cr_configfile: operations/monitoring/helm/cr.yaml
      ct_configfile: operations/monitoring/helm/ct.yaml
    secrets:
      vault_repo_secret_name: grafana-pyroscope-releases
