on: issue_comment

jobs:
  pyrobench:
    name: Run Pyrobench on demand by PR comment
    if: ${{ (github.event.issue.pull_request) && contains(github.event.comment.body, '@pyrobench') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Pyrobench
        uses: grafana/pyrobench@main
        with:
          github_context: ${{ toJson(github) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
