name: JS Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, size-limit-action]

jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Webapp dependencies
        run: yarn install
      - name: Run Webapp tests
        run: yarn run test
      - name: Run Webapp lints
        run: yarn lint
      - name: Run Webapp Format check
        run: yarn format:check
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install
          build_script: build:size-limit
