name: Update Contributors in README

on:
  schedule:
    - cron: '0 0 1-7 * SUN'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  update-contributors:
    if: github.repository == 'grafana/pyroscope'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: 'false'
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@eb33f84481d38701f4d2c587a4817ce332784f5f
        with:
          repo_secrets: |
            GITHUB_APP_ID=pyroscope-development-app:app-id
            GITHUB_APP_INSTALLATION_ID=pyroscope-development-app:app-installation-id
            GITHUB_APP_PRIVATE_KEY=pyroscope-development-app:private-key

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ env.GITHUB_APP_ID }}
          private-key: ${{ env.GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            pyroscope
      - name: Get GitHub App User ID
        id: get-user-id
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          APP_BOT="${{ steps.generate_token.outputs.app-slug }}[bot]"
          echo "user-id=$(gh api "/users/${APP_BOT}" --jq .id)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: 1.24.10
      - name: Update contributors
        run: make update-contributors

      - name: Commit and push changes
        run: |
          APP_BOT="${{ steps.generate_token.outputs.app-slug }}[bot]"
          git config --local user.name "${APP_BOT}"
          git config --local user.email "${{ steps.get-user-id.outputs.user-id }}+${APP_BOT}@users.noreply.github.com"
          if ! git diff --exit-code README.md; then
              git add README.md
              git commit -m 'docs: updates the list of contributors in README'
              gh auth status
              git push --force https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}.git HEAD:main 2> /dev/null
          fi
